task_manager/statuses/urls.py
from django.urls import path

from . import views

app_name = 'statuses'

urlpatterns = [
    path('', views.StatusListView.as_view(), name='list'),
    path('create/', views.StatusCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.StatusUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.StatusDeleteView.as_view(), name='delete'),
]

task_manager/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path
from django.views.i18n import set_language

from task_manager import views
from task_manager.debug_view import DebugInfoView

urlpatterns = [
    path('set-language/', set_language, name='set_language'),
    path('__debug__/info/', DebugInfoView.as_view(), name='debug-env')
]

urlpatterns += i18n_patterns(
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('admin/', admin.site.urls),
)

task_manager/statuses/models.py
from django.db import models


class Status(models.Model):
    name = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/statuses/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Status


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = 'name',

        labels = {
            'name': _('Name'),
        }

task_manager/statuses/views.py
import logging

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.deletion import ProtectedError
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    UpdateView,
)

from task_manager.mixins import StrictLoginRequiredMessageMixin
from task_manager.utils.request import format_ip_log

from .forms import StatusForm
from .models import Status

logger = logging.getLogger(__name__)


class StatusListView(StrictLoginRequiredMessageMixin, ListView):
    model = Status
    context_object_name = 'statuses'
    template_name = 'statuses/list.html'


class StatusUpdateView(LoginRequiredMixin, UpdateView):
    model = Status
    form_class = StatusForm
    template_name = 'statuses/update.html'
    success_url = reverse_lazy('statuses:list')

    def form_valid(self, form):
        response = super().form_valid(form)
        status = form.instance
        messages.success(self.request, _('Status successfully updated'))
        logger.info(f'✏️ Status successfully updated: {status} '
                    f'{format_ip_log(self.request)}')
        return response


class StatusCreateView(LoginRequiredMixin, CreateView):
    model = Status
    form_class = StatusForm
    template_name = 'statuses/create.html'
    success_url = reverse_lazy('statuses:list')

    def form_valid(self, form):
        response = super().form_valid(form)
        status = form.instance
        messages.success(self.request, _('Status successfully created'))
        logger.info(f'✅ New status created: {status} '
                    f'{format_ip_log(self.request)}')
        return response


class StatusDeleteView(LoginRequiredMixin, DeleteView):
    model = Status
    template_name = 'statuses/delete.html'
    success_url = reverse_lazy('statuses:list')
    context_object_name = 'status'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        try:
            self.object.delete()
            messages.success(request, _('Status successfully deleted'))
            logger.info(
                f'❌ Status deleted: {self.object} {format_ip_log(request)}'
            )
        except ProtectedError:
            messages.error(
                request,
                _('Cannot delete status because '
                  'it is in use by one or more tasks.')
            )
            logger.warning(
                f'⚠️ Attempted to delete status in use: '
                f'{self.object} {format_ip_log(request)}'
            )
        return redirect(self.success_url)

task_manager/statuses/templates/statuses/create.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1 class="my-4">{% trans "Create status" %}</h1>
  {% include "statuses/partials/form.html" with button_text=_("Create") %}
{% endblock %}
{% block footer %}
  {% include "partials/footer.html" %}
{% endblock %}

task_manager/statuses/templates/statuses/delete.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1 class="my-4">{% trans "Delete status" %}</h1>
  <p>
    {% trans "Are you sure you want to delete " %}
    <b>{{ status }}</b>?
  </p>
  <form method="post">
    {% csrf_token %}
    <input class="btn btn-danger"
           type="submit"
           value="{% trans 'Yes, delete' %}">
    <a class="btn btn-secondary" href="{% url 'statuses:list' %}">{% trans "Cancel" %}</a>
  </form>
{% endblock %}
{% block footer %}
  {% include "partials/footer.html" %}
{% endblock %}

task_manager/statuses/templates/statuses/list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1 class="my-4">{% trans "Statuses" %}</h1>
  <a class="btn btn-primary mb-3" href="{% url 'statuses:create' %}">{% trans "Create status" %}</a>
  <!--    TODO: Add bootstrap utilities to control table columns width:-->
  <!--    w-10, w-20 or smth-->
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>{% trans "Name" %}</th>
        <th>{% trans "Created" %}</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for status in statuses %}
        <tr>
          <td>{{ status.id }}</td>
          <td>{{ status.name }}</td>
          <td>{{ status.created_at|date:"d.m.Y h:m" }}</td>
          <td>
            <a href="{% url 'statuses:update' status.id %}">{% trans "Edit" %}</a>
            <br>
            <a href="{% url 'statuses:delete' status.id %}">{% trans "Delete" %}</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

task_manager/statuses/templates/statuses/update.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1 class="my-4">{% trans "Edit status" %}</h1>
  {% include "statuses/partials/form.html" with button_text=_("Update") %}
{% endblock %}
{% block footer %}
  {% include "partials/footer.html" %}
{% endblock %}