task_manager/labels/urls.py
from django.urls import path

from . import views

app_name = 'labels'

urlpatterns = [
    path('', views.LabelListView.as_view(), name='list'),
    path('create/', views.LabelCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.LabelUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.LabelDeleteView.as_view(), name='delete'),
]

task_manager/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path
from django.views.i18n import set_language

from task_manager import views
from task_manager.debug_view import DebugInfoView

urlpatterns = [
    path('set-language/', set_language, name='set_language'),
    path('__debug__/info/', DebugInfoView.as_view(), name='debug-env')
]

urlpatterns += i18n_patterns(
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('admin/', admin.site.urls),
)

task_manager/labels/models.py
from django.db import models


class Label(models.Model):
    name = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/labels/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Label


class LabelForm(forms.ModelForm):
    class Meta:
        model = Label
        fields = 'name',

        labels = {
            'name': _('Name'),
        }

task_manager/labels/views.py
import logging

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    UpdateView,
)

from task_manager.mixins import StrictLoginRequiredMessageMixin
from task_manager.utils.request import format_ip_log

from .forms import LabelForm
from .models import Label

logger = logging.getLogger(__name__)


class LabelListView(StrictLoginRequiredMessageMixin, ListView):
    model = Label
    context_object_name = 'labels'
    template_name = 'labels/list.html'


class LabelUpdateView(LoginRequiredMixin, UpdateView):
    model = Label
    form_class = LabelForm
    template_name = 'labels/update.html'
    success_url = reverse_lazy('labels:list')

    def form_valid(self, form):
        response = super().form_valid(form)
        label = form.instance
        messages.success(self.request, _('Label successfully updated'))
        logger.info(f'✏️ Label successfully updated: {label} '
                    f'{format_ip_log(self.request)}')
        return response


class LabelCreateView(LoginRequiredMixin, CreateView):
    model = Label
    form_class = LabelForm
    template_name = 'labels/create.html'
    success_url = reverse_lazy('labels:list')

    def form_valid(self, form):
        response = super().form_valid(form)
        label = form.instance
        messages.success(self.request, _('Label successfully created'))
        logger.info(f'✅ New label created: {label} '
                    f'{format_ip_log(self.request)}')
        return response


class LabelDeleteView(LoginRequiredMixin, DeleteView):
    model = Label
    template_name = 'labels/delete.html'
    success_url = reverse_lazy('labels:list')
    context_object_name = 'label'

    def post(self, request, *args, **kwargs):
        label = self.get_object()
        if self._is_in_use(label):
            messages.error(
                request,
                _('Cannot delete label because '
                  'it is in use by one or more tasks.')
            )
            logger.warning(
                f'⚠️ Attempted to delete label in use: '
                f'{label} {format_ip_log(request)}'
            )
        else:
            label.delete()
            messages.success(request, _('Label successfully deleted'))
            logger.info(
                f'❌ Label deleted: {label} {format_ip_log(request)}'
            )
        return redirect(self.success_url)

    @staticmethod
    def _is_in_use(label):
        return label.task_set.exists()

task_manager/labels/templates/labels/create.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1 class="my-4">{% trans "Create label" %}</h1>
  {% include "labels/partials/form.html" with button_text=_("Create") %}
{% endblock %}
{% block footer %}
  {% include "partials/footer.html" %}
{% endblock %}

task_manager/labels/templates/labels/delete.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1 class="my-4">{% trans "Delete label" %}</h1>
  <p>
    {% trans "Are you sure you want to delete " %}
    <b>{{ label }}</b>?
  </p>
  <form method="post">
    {% csrf_token %}
    <input class="btn btn-danger"
           type="submit"
           value="{% trans 'Yes, delete' %}">
    <a class="btn btn-secondary" href="{% url 'labels:list' %}">{% trans "Cancel" %}</a>
  </form>
{% endblock %}
{% block footer %}
  {% include "partials/footer.html" %}
{% endblock %}

task_manager/labels/templates/labels/list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1 class="my-4">{% trans "Labels" %}</h1>
  <a class="btn btn-primary mb-3" href="{% url 'labels:create' %}">{% trans "Create label" %}</a>
  <!--    TODO: Add bootstrap utilities to control table columns width:-->
  <!--    w-10, w-20 or smth-->
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>{% trans "Name" %}</th>
        <th>{% trans "Created" %}</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for label in labels %}
        <tr>
          <td>{{ label.id }}</td>
          <td>{{ label.name }}</td>
          <td>{{ label.created_at|date:"d.m.Y h:m" }}</td>
          <td>
            <a href="{% url 'labels:update' label.id %}">{% trans "Edit" %}</a>
            <br>
            <a href="{% url 'labels:delete' label.id %}">{% trans "Delete" %}</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

task_manager/labels/templates/labels/update.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1 class="my-4">{% trans "Edit label" %}</h1>
  {% include "labels/partials/form.html" with button_text=_("Update") %}
{% endblock %}
{% block footer %}
  {% include "partials/footer.html" %}
{% endblock %}