task_manager/tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.TaskListView.as_view(), name='list'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('<int:pk>/', views.TaskDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', views.TaskUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name='delete'),
]

task_manager/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path
from django.views.i18n import set_language

from task_manager import views
from task_manager.debug_view import DebugInfoView

urlpatterns = [
    path('set-language/', set_language, name='set_language'),
    path('__debug__/info/', DebugInfoView.as_view(), name='debug-env')
]

urlpatterns += i18n_patterns(
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('admin/', admin.site.urls),
)

task_manager/tasks/models.py
from django.db import models

from task_manager.labels.models import Label
from task_manager.statuses.models import Status
from task_manager.users.models import CustomUser


class Task(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(blank=True)
    status = models.ForeignKey(Status, on_delete=models.PROTECT,
                               related_name='tasks')
    labels = models.ManyToManyField(Label, blank=True)
    author = models.ForeignKey(CustomUser, on_delete=models.PROTECT,
                               related_name='authored_tasks')
    executor = models.ForeignKey(CustomUser, on_delete=models.PROTECT,
                                 related_name='executed_tasks')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/tasks/forms.py
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from .models import Task


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ('name', 'description', 'status', 'executor', 'labels')

        labels = {
            'name': _('Name'),
            'description':  _('Description'),
            'status':   _('Status'),
            'executor':   _('Executor'),
            'labels':   _('Labels'),
        }

task_manager/tasks/views.py
import logging

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView
from django_filters.views import FilterView

from task_manager.mixins import StrictLoginRequiredMessageMixin
from task_manager.utils.request import format_ip_log

from .filters import TaskFilter
from .forms import TaskForm
from .models import Task

logger = logging.getLogger(__name__)


class TaskListView(StrictLoginRequiredMessageMixin, FilterView):
    model = Task
    filterset_class = TaskFilter
    template_name = 'tasks/list.html'
    context_object_name = 'tasks'

    def get_filterset(self, filterset_class):
        return filterset_class(
            self.request.GET,
            request=self.request,
            queryset=self.get_queryset()
        )


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = 'tasks/show.html'
    context_object_name = 'task'


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/create.html'
    success_url = reverse_lazy('tasks:list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        response = super().form_valid(form)
        task = form.instance
        messages.success(self.request, _('Task successfully created'))
        logger.info(f'✅ New task created: {task} '
                    f'{format_ip_log(self.request)}')
        return response


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/update.html'
    success_url = reverse_lazy('tasks:list')

    def form_valid(self, form):
        response = super().form_valid(form)
        task = form.instance
        messages.success(self.request, _('Task successfully updated'))
        logger.info(f'✏️ Task updated: {task} '
                    f'{format_ip_log(self.request)}')
        return response


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    template_name = 'tasks/delete.html'
    success_url = reverse_lazy('tasks:list')
    context_object_name = 'task'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()

        self.object = self.get_object()
        if self.object.author != request.user:
            messages.error(request, _('Only the author can delete the task.'))
            message = (f'🚫 Attempt to delete task {self.object} '
                       f'with foreign authorization {format_ip_log(request)}')
            logger.warning(message)
            return redirect(self.success_url)

        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logger.info(f'🗑️ Task deleted: {self.object} {format_ip_log(request)}')
        messages.success(request, _('Task successfully deleted'))
        return super().post(request, *args, **kwargs)

task_manager/tasks/templates/tasks/create.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1 class="my-4">{% trans "Create task" %}</h1>
  {% include "tasks/partials/form.html" with button_text=_("Create") %}
{% endblock %}
{% block footer %}
  {% include "partials/footer.html" %}
{% endblock %}

task_manager/tasks/templates/tasks/delete.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1 class="my-4">{% trans "Delete task" %}</h1>
  <p>
    {% trans "Are you sure you want to delete " %} <b>{{ task }}</b>?
  </p>
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="confirm" value="true">
    <button type="submit" class="btn btn-danger">{% trans "Yes, delete" %}</button>
    <a href="{% url 'tasks:list' %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
  </form>
{% endblock %}

task_manager/tasks/templates/tasks/list.html
{% extends "base.html" %}
{% load crispy_forms_tags i18n %}
{% block content %}
  <h1 class="my-4">{% trans "Tasks" %}</h1>
  <a class="btn btn-primary mb-3" href="{% url 'tasks:create' %}">{% trans "Create task" %}</a>
  <div class="card mb-3">
    <div class="card-body bg-light">
      <form method="get">
        {% csrf_token %}
        {{ filter.form|crispy }}
        <button type="submit" class="btn btn-primary">{% trans "Show" %}</button>
      </form>
    </div>
  </div>
  <!--    TODO: Add bootstrap utilities to control table columns width:-->
  <!--    w-10, w-20 or smth-->
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>{% trans "Name" %}</th>
        <th>{% trans "Status" %}</th>
        <th>{% trans "Author" %}</th>
        <th>{% trans "Executor" %}</th>
        <th>{% trans "Created" %}</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for task in tasks %}
        <tr>
          <td>{{ task.id }}</td>
          <td>
            <a href="{% url 'tasks:detail' task.id %}">{{ task.name }}</a>
          </td>
          <td>{{ task.status }}</td>
          <td>{{ task.author.full_name }}</td>
          <td>{{ task.executor.full_name }}</td>
          <td>{{ task.created_at|date:"d.m.Y h:m" }}</td>
          <td>
            <a href="{% url 'tasks:update' task.id %}">{% trans "Edit" %}</a>
            <br>
            <a href="{% url 'tasks:delete' task.id %}">{% trans "Delete" %}</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

task_manager/tasks/templates/tasks/show.html
{% extends "base.html" %}
<!--{% load i18n %}-->
{% load crispy_forms_tags i18n %}
{% block content %}
  <h1 class="my-4">{% trans "Task View " %}</h1>
  <a class="btn btn-primary mb-3" href="{% url 'tasks:create' %}">{% trans "Create task" %}</a>
  <!--    TODO: Add bootstrap utilities to control table columns width:-->
  <!--    w-10, w-20 or smth-->
  <div class="card">
    <div class="card-header bg-secondary text-white">
      <h2>{{ task.name }}</h2>
    </div>
    <div class="card-body bg-light">
      <p>{{ task.description }}</p>
      <hr>
      <div class="container">
        <div class="row p-1">
          <div class="col">{% trans "Author" %}</div>
          <div class="col">{{ task.author.full_name }}</div>
        </div>
        <div class="row p-1">
          <div class="col">{% trans "Executor" %}</div>
          <div class="col">{{ task.executor.full_name }}</div>
        </div>
        <div class="row p-1">
          <div class="col">{% trans "Status" %}</div>
          <div class="col">{{ task.status }}</div>
        </div>
        <div class="row p-1">
          <div class="col">{% trans "Created" %}</div>
          <div class="col">{{ task.created_at|date:"d.m.Y H:i" }}</div>
        </div>
        <div class="row p-1">
          <div class="col">
            <h6>{% trans "Labels" %}</h6>
            <ul>
              {% for label in task.labels.all %}<li>{{ label.name }}</li>{% endfor %}
            </ul>
          </div>
        </div>
        <div class="row p-1">
          <div class="col">
            <a href="{% url 'tasks:update' task.pk %}">{% trans 'Update' %}</a>
            <br>
            <a href="{% url 'tasks:delete' task.pk %}">{% trans 'Delete' %}</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

task_manager/tasks/templates/tasks/update.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1 class="my-4">{% trans "Edit task" %}</h1>
  {% include "tasks/partials/form.html" with button_text=_("Update") %}
{% endblock %}
{% block footer %}
  {% include "partials/footer.html" %}
{% endblock %}