task_manager/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path
from django.views.i18n import set_language

from task_manager import views
from task_manager.debug_view import DebugInfoView

urlpatterns = [
    path('set-language/', set_language, name='set_language'),
    path('__debug__/info/', DebugInfoView.as_view(), name='debug-env')
]

urlpatterns += i18n_patterns(
    path('', views.IndexView.as_view(), name='index'),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('admin/', admin.site.urls),
)

task_manager/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('', views.UserListView.as_view(), name='list'),
    path('create/', views.UserRegisterView.as_view(), name='create'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('<int:pk>/update/', views.UserUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.UserDeleteView.as_view(), name='delete'),
]

task_manager/users/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    @property
    def full_name(self):
        fn = f'{self.first_name} {self.last_name}'.strip()
        return fn if fn else self.username

    def __str__(self):
        return self.full_name

task_manager/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import gettext_lazy as _

from .models import CustomUser


class CustomUserForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'username')

        labels = {
            'first_name': _('First name'),
            'last_name':  _('Last name'),
            'username':   _('Username'),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Delete all the password field validators
        self.fields['password1'].validators.clear()

        # Update the password field help_text
        self.fields['password1'].help_text = _(
            'Your password must contain at least 3 characters.')
        self.fields['password2'].help_text = _(
            'Enter the same password again for verification.')

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and len(password1) < 3:
            raise forms.ValidationError(
                _('Your password is too short. '
                  'Password must be at least 3 characters.'))

        return password2


class CustomUserUpdateForm(CustomUserForm):
    def clean_username(self):
        username = self.cleaned_data.get('username')
        qs = CustomUser.objects.filter(username=username)
        if self.instance.pk:
            qs = qs.exclude(pk=self.instance.pk)
        if qs.exists():
            raise forms.ValidationError(
                _('User with this username already exists.'))
        return username

task_manager/users/views.py
import logging

from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LogoutView
from django.db.models.deletion import ProtectedError
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.views.generic import CreateView, ListView, UpdateView

from task_manager.utils.request import format_ip_log

from .forms import CustomUserForm, CustomUserUpdateForm
from .mixins import UserAccessMixin
from .models import CustomUser

logger = logging.getLogger(__name__)


class UserListView(ListView):
    model = CustomUser
    context_object_name = 'users'
    template_name = 'users/list.html'

    def get(self, request, *args, **kwargs):
        logger.info(f'👥 User list viewed by {self.request.user} '
                     f'{format_ip_log(self.request)}')
        return super().get(request, *args, **kwargs)


class UserRegisterView(CreateView):
    form_class = CustomUserForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('login')

    def form_valid(self, form):
        response = super().form_valid(form)
        user = form.instance
        messages.success(self.request, _('User successfully registered'))
        logger.info(f'🆕👤 New user registered: {user} '
                    f'{format_ip_log(self.request)}')
        return response


class UserLogoutView(LogoutView):
    next_page = 'index'
    
    def post(self, request, *args, **kwargs):
        user = request.user
        logger.info(
            f'🚪 {user} logged out {format_ip_log(self.request)}')
        messages.info(
            request, _('You have successfully logged out of the system'))
        return super().post(request, *args, **kwargs)


class UserUpdateView(
    LoginRequiredMixin, UserAccessMixin, UserPassesTestMixin, UpdateView):
    model = CustomUser
    form_class = CustomUserUpdateForm
    template_name = 'users/update.html'
    success_url = reverse_lazy('users:list')

    def test_func(self):
        return self.request.user.pk == self.kwargs['pk']

    def form_valid(self, form):
        user = form.instance
        logger.info(
            f'✅ User {user} was successfully updated '
            f'{format_ip_log(self.request)}')
        messages.success(
            self.request,
            _('User successfully updated'))
        return super().form_valid(form)


# TODO: refactor using generic views and mixins
class UserDeleteView(View):
    redirect_url = reverse_lazy('users:list')

    def get(self, request, pk):
        check = self._check_permissions(request, pk)
        if check:
            return check
        return render(request, 'users/delete.html')

    def post(self, request, pk):
        check = self._check_permissions(request, pk)
        if check:
            return check

        user = get_object_or_404(CustomUser, pk=pk)

        if request.POST.get('confirm') != 'true':
            return redirect(self.redirect_url)

        try:
            logger.info(f'📄 Current user: {user} '
                        f'{format_ip_log(self.request)}')
            user.delete()
            logout(request)
            messages.success(request, _('User was successfully deleted.'))
            logger.info(f'🗑️ Deleting user: {user} '
                        f'{format_ip_log(self.request)}')
        except ProtectedError:
            messages.error(
                request,
                _('Cannot delete user because '
                  'it is in use by one or more tasks.')
            )
            logger.warning(
                f'⚠️ Attempted to delete user in use: '
                f'{user} {format_ip_log(request)}'
            )

        return redirect(self.redirect_url)

    def _check_permissions(self, request, pk):
        if not request.user.is_authenticated:
            messages.error(request, _(
                'You are not authorized! Please log in.'))
            return redirect('login')

        if request.user.pk != pk:
            messages.error(request, _(
                'You do not have permission to modify another user.'))
            return redirect('users:list')

        return None

task_manager/users/templates/users/delete.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1 class="my-4">{% trans "Delete user" %}</h1>
  <p>
    {% trans "Are you sure you want to delete " %} <b>{{ request.user.full_name }}</b>?
  </p>
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="confirm" value="true">
    <button type="submit" class="btn btn-danger">{% trans "Yes, delete" %}</button>
    <a href="{% url 'users:list' %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
  </form>
{% endblock %}

task_manager/users/templates/users/list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1 class="my-4">{% trans "Users" %}</h1>
  <!--    TODO: Add bootstrap utilities to control table columns width:-->
  <!--    w-10, w-20 or smth-->
  <table class="table table-striped">
    <thead>
      <tr>
        <th>ID</th>
        <th>{% trans "Username" %}</th>
        <th>{% trans "Full name" %}</th>
        <th>{% trans "Created" %}</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
        <tr>
          <td>{{ user.id }}</td>
          <td>{{ user.username }}</td>
          <td>{{ user.full_name }}</td>
          <td>{{ user.date_joined|date:"d.m.Y h:m" }}</td>
          <td>
            <a href="{% url 'users:update' user.id %}">{% trans "Edit" %}</a>
            <br>
            <a href="{% url 'users:delete' user.id %}">{% trans "Delete" %}</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

task_manager/users/templates/users/register.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1 class="my-4">{% trans "Sign up" %}</h1>
  {% include "users/partials/form.html" with button_text=_("Register") %}
{% endblock %}
{% block footer %}
  {% include "partials/footer.html" %}
{% endblock %}

task_manager/users/templates/users/update.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <h1 class="my-4">{% trans "Edit user" %}</h1>
  {% include "users/partials/form.html" with button_text=_("Update") %}
{% endblock %}
{% block footer %}
  {% include "partials/footer.html" %}
{% endblock %}